# Generated by Django 4.2.1 on 2023-05-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('idOeuvre', models.AutoField(primary_key=True, serialize=False)),
                ('nomOeuvre', models.CharField(max_length=50, verbose_name="Nom de l'oeuvre")),
            ],
        ),
    ]
