# Generated by Django 4.2.1 on 2023-05-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliArtSpectra', '0002_oeuvre_datecreationoeuvre_oeuvre_descriptionoeuvre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeuvre',
            name='dateCreationOeuvre',
            field=models.CharField(default='1900-01-01', max_length=10, verbose_name="Date de création de l'oeuvre"),
        ),
    ]
