# Generated by Django 4.2.1 on 2023-05-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliArtSpectra', '0003_alter_oeuvre_datecreationoeuvre'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeuvre',
            name='imageOeuvre',
            field=models.ImageField(blank=True, default='', upload_to='images/oeuvres/', verbose_name="Image de l'oeuvre"),
        ),
    ]
