# Generated by Django 4.2.1 on 2023-05-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliArtSpectra', '0004_oeuvre_imageoeuvre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeuvre',
            name='dateCreationOeuvre',
            field=models.CharField(max_length=10, verbose_name="Date de création de l'oeuvre"),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='dimensionOeuvre',
            field=models.CharField(blank=True, max_length=50, verbose_name="Dimension de l'oeuvre"),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='imageOeuvre',
            field=models.ImageField(blank=True, upload_to='images/oeuvres/', verbose_name="Image de l'oeuvre"),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='nomOeuvre',
            field=models.CharField(max_length=50, unique=True, verbose_name="Nom de l'oeuvre"),
        ),
    ]
