# Generated by Django 4.2.1 on 2023-05-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliArtSpectra', '0005_alter_oeuvre_datecreationoeuvre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeuvre',
            name='slug',
            field=models.SlugField(default='tableau', max_length=100, verbose_name="Slug de l'oeuvre"),
            preserve_default=False,
        ),
    ]
