# Generated by Django 4.2.2 on 2023-06-07 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appliArtSpectra', '0006_oeuvre_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='auteurOeuvre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Auteur de l'oeuvre"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='prixOeuvre',
            field=models.IntegerField(default=20, verbose_name="Prix de l'oeuvre"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='quantiteOeuvre',
            field=models.IntegerField(default=5, verbose_name="Quantité de l'oeuvre"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PanierOeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliArtSpectra.oeuvre')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliArtSpectra.panier')),
            ],
            options={
                'db_table': 'panier_oeuvre',
            },
        ),
        migrations.AddField(
            model_name='panier',
            name='oeuvre',
            field=models.ManyToManyField(through='appliArtSpectra.PanierOeuvre', to='appliArtSpectra.oeuvre'),
        ),
        migrations.AddField(
            model_name='panier',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
