# Generated by Django 4.2.2 on 2023-06-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/avatars/', verbose_name='Image de profil'),
        ),
        migrations.AddField(
            model_name='shopper',
            name='presentation',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
